name:                oko
version:             0.1.0.0
github:              "jonringer/oko"
license:             BSD3
author:              "Jonathan Ringer"
maintainer:          "jringer117@gmail.com"
copyright:           "2018 Jonathan Ringer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Command Line runner for projects
category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jonringer/oko#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- megaparsec
- ansi-terminal
- system-filepath

library:
  source-dirs: src

executables:
  oko-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oko 

tests:
  oko-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oko
    - hspec
    - hspec-megaparsec
    - QuickCheck
